import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, Brain, Check, Dna, Fingerprint, HeartPulse, Leaf, MousePointer2, Radio, Sparkles } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

const auditDeck = [
  { title: 'Metabolic drift', value: '−18%', note: 'Glucose volatility reduced' },
  { title: 'Sleep aperture', value: '+42m', note: 'Deep phase expanded' },
  { title: 'Inflammation load', value: '0.31', note: 'CRP trajectory stabilized' },
];

const feed = [
  'Optimizing Circadian Rhythm...',
  'Mapping micronutrient absorption...',
  'Reconciling recovery debt...',
  'Calibrating adaptive regimen...',
];

function Navbar(){
  const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const on=()=>setScrolled(scrollY>40);on();addEventListener('scroll',on);return()=>removeEventListener('scroll',on)},[]);
  return <nav className={`fixed left-1/2 top-5 z-50 flex -translate-x-1/2 items-center gap-8 rounded-full px-5 py-3 transition-all duration-500 ${scrolled?'border border-[#2E4036]/10 bg-white/60 text-[#2E4036] shadow-2xl shadow-black/5 backdrop-blur-xl':'text-white'}`}>
    <a className="flex items-center gap-2 font-bold tracking-tight" href="#top"><Leaf size={18}/> Nura</a>
    <div className="hidden gap-6 text-xs font-semibold uppercase tracking-[.22em] md:flex"><a href="#features">Intelligence</a><a href="#manifesto">Manifesto</a><a href="#protocol">Protocol</a></div>
    <a href="#membership" className="magnetic rounded-full border border-current px-4 py-2 text-xs font-bold uppercase tracking-widest"><span>Apply</span></a>
  </nav>
}

function Hero(){return <section id="top" className="hero-bg relative flex h-[100dvh] items-end overflow-hidden p-6 md:p-12"><div className="hero-copy mb-10 max-w-6xl text-white"><div className="mb-5 inline-flex rounded-full border border-white/25 bg-white/10 px-4 py-2 mono text-xs uppercase tracking-[.28em] backdrop-blur">Clinical boutique // organic intelligence</div><h1 className="max-w-5xl text-6xl font-extrabold leading-[.88] tracking-[-.07em] md:text-8xl lg:text-[9rem]">Nature is the <span className="serif block font-semibold italic tracking-[-.04em] text-[#F2F0E9]">Algorithm.</span></h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-white/78">A precision health instrument that translates biology, behavior, and recovery into living protocols — designed with the restraint of a lab and the seduction of a luxury editorial.</p></div></section>}

function Features(){const [deck,setDeck]=useState(auditDeck);const [msg,setMsg]=useState(0);useEffect(()=>{const a=setInterval(()=>setDeck(d=>{const n=[...d];n.unshift(n.pop());return n}),2100);const b=setInterval(()=>setMsg(m=>(m+1)%feed.length),1900);return()=>{clearInterval(a);clearInterval(b)}},[]);return <section id="features" className="px-5 py-28 md:px-10"><div className="mx-auto max-w-7xl"><div className="mb-12 flex flex-col justify-between gap-6 md:flex-row"><h2 className="max-w-3xl text-5xl font-black tracking-[-.06em] md:text-7xl">Precision micro-UI for human systems.</h2><p className="max-w-md text-[#1A1A1A]/60">Functional software-feeling cards: shuffling diagnostics, live neural telemetry, and automated regimen scheduling.</p></div><div className="grid gap-5 lg:grid-cols-3">
    <div className="dash-card rounded-[3rem] bg-white p-7"><Brain className="text-[#CC5833]"/><h3 className="mt-5 text-2xl font-bold">Audit Intelligence</h3><div className="relative mt-8 h-64">{deck.map((c,i)=><div key={c.title} className="audit-card absolute left-0 right-0 rounded-[2rem] border border-[#2E4036]/10 bg-white p-6" style={{transform:`translateY(${i*34}px) scale(${1-i*.05})`,zIndex:5-i,opacity:1-i*.18}}><div className="mono text-xs uppercase text-[#2E4036]/50">Diagnostic shuffler</div><div className="mt-4 flex items-end justify-between"><b className="text-xl">{c.title}</b><span className="serif text-5xl italic text-[#CC5833]">{c.value}</span></div><p className="mt-3 text-sm text-black/50">{c.note}</p></div>)}</div></div>
    <div className="dash-card rounded-[3rem] bg-[#2E4036] p-7 text-white"><Radio className="text-[#CC5833]"/><h3 className="mt-5 text-2xl font-bold">Neural Stream</h3><div className="mt-8 rounded-[2rem] bg-black/20 p-5 mono text-sm"><div className="mb-5 flex items-center gap-2 text-white/50"><span className="h-2 w-2 animate-pulse rounded-full bg-[#CC5833]"/> LIVE TELEMETRY</div><p className="min-h-16 text-xl text-[#F2F0E9]">{feed[msg]}<span className="ml-1 animate-pulse text-[#CC5833]">▌</span></p><div className="mt-8 grid grid-cols-2 gap-3 text-xs text-white/55"><span>HRV 72ms</span><span>REM +14%</span><span>VO₂ 48.2</span><span>Load 0.64</span></div></div></div>
    <div className="dash-card relative overflow-hidden rounded-[3rem] bg-white p-7"><MousePointer2 className="text-[#CC5833]"/><h3 className="mt-5 text-2xl font-bold">Adaptive Regimen</h3><div className="relative mt-8 grid grid-cols-7 gap-2 rounded-[2rem] bg-[#F2F0E9] p-4">{Array.from({length:28}).map((_,i)=><div key={i} className={`h-10 rounded-xl ${i%5===0?'bg-[#CC5833]':'bg-white'} ${i%7===2?'ring-2 ring-[#2E4036]':''}`}/>) }<MousePointer2 className="cursor-path absolute text-[#1A1A1A] drop-shadow-xl"/></div><p className="mt-6 mono text-xs uppercase tracking-widest text-black/45">Mock cursor protocol scheduler</p></div>
  </div></div></section>}

function Manifesto(){return <section id="manifesto" className="texture-bg manifesto overflow-hidden rounded-[4rem] px-6 py-32 text-white md:px-12"><div className="mx-auto max-w-6xl"><p className="mono mb-10 text-[#CC5833]">THE MANIFESTO</p><h2 className="split text-5xl font-black leading-tight tracking-[-.06em] md:text-8xl">We stop asking <span className="serif italic text-white/60">what is wrong?</span><br/>We begin measuring <span className="serif italic text-[#F2F0E9]">what is optimal.</span></h2></div></section>}

function Protocol(){const cards=[['01','Biological Capture','Rotating double-helix artifact maps recovery, nutrition, and stress signatures.',<Dna className="helix h-28 w-28 text-[#CC5833]"/>],['02','Laser Grid Analysis','A scanning lattice reconciles contradictions between subjective feeling and clinical signal.',<div className="relative h-32 w-32 overflow-hidden rounded-3xl border border-[#2E4036]/20 bg-[linear-gradient(90deg,rgba(46,64,54,.12)_1px,transparent_1px),linear-gradient(rgba(46,64,54,.12)_1px,transparent_1px)] bg-[size:18px_18px]"><div className="scanner absolute inset-x-0 h-10"/></div>],['03','Adaptive Output','Protocols pulse like an EKG: never static, always adjusting to the body in front of us.',<svg className="ekg h-28 w-40" viewBox="0 0 220 90"><path d="M0 45 H42 L55 18 L74 72 L94 38 L112 45 H220" fill="none" stroke="#CC5833" strokeWidth="5" strokeLinecap="round"/></svg>]];return <section id="protocol" className="px-5 py-28 md:px-10"><div className="mx-auto max-w-5xl">{cards.map((c,i)=><div key={c[0]} className="protocol-card sticky top-20 mb-8 flex min-h-[70vh] flex-col justify-between rounded-[3rem] border border-[#2E4036]/10 bg-[#F8F6EF] p-8 shadow-2xl shadow-black/10 md:p-12" style={{zIndex:i+1}}><div className="flex justify-between mono text-sm text-[#2E4036]/55"><span>ARCHIVE / {c[0]}</span><span>NURA SYSTEM</span></div><div className="grid items-end gap-8 md:grid-cols-[1fr_auto]"><div><h3 className="text-5xl font-black tracking-[-.05em] md:text-7xl">{c[1]}</h3><p className="mt-6 max-w-lg text-lg text-black/55">{c[2]}</p></div>{c[3]}</div></div>)}</div></section>}

function Membership(){return <section id="membership" className="px-5 pb-8 md:px-10"><div className="grid gap-5 lg:grid-cols-3">{['Baseline','Performance','Concierge'].map((t,i)=><div key={t} className={`rounded-[3rem] p-8 ${i===1?'bg-[#2E4036] text-white':'bg-white'}`}><Sparkles className={i===1?'text-[#CC5833]':'text-[#2E4036]'}/><h3 className="mt-6 text-3xl font-bold">{t}</h3><p className="mt-3 text-sm opacity-60">Adaptive health intelligence for {i===0?'foundation building':i===1?'high-output lives':'private clinical partnership'}.</p><div className="my-8 serif text-6xl italic">${[280,640,1200][i]}</div><button className={`magnetic w-full rounded-full px-6 py-4 font-bold ${i===1?'bg-[#CC5833]':'border border-[#2E4036]/20'}`}><span>Request access</span></button><ul className="mt-8 space-y-3 text-sm">{['Longitudinal dashboard','Weekly protocol updates','Clinical signal review'].map(x=><li className="flex gap-2" key={x}><Check size={16}/>{x}</li>)}</ul></div>)}</div><footer className="mt-8 rounded-t-[4rem] bg-[#1A1A1A] p-10 text-white md:p-16"><div className="flex flex-col justify-between gap-10 md:flex-row"><h2 className="text-5xl font-black tracking-[-.06em]">Nura Health</h2><div className="mono flex items-center gap-3 text-sm"><span className="h-3 w-3 animate-pulse rounded-full bg-[#CC5833]"/> System Operational</div><a className="flex items-center gap-2 text-[#F2F0E9]" href="#top">Return to surface <ArrowUpRight size={18}/></a></div></footer></section>}

export default function App(){useEffect(()=>{const ctx=gsap.context(()=>{gsap.from('.hero-copy > *',{y:40,opacity:0,duration:1.1,stagger:.16,ease:'power3.out'});gsap.from('.split',{scrollTrigger:{trigger:'.manifesto',start:'top 70%'},y:80,opacity:0,duration:1.2,ease:'power3.out'});gsap.utils.toArray('.protocol-card').forEach((card,i)=>{ScrollTrigger.create({trigger:card,start:'top 22%',end:'bottom 25%',onEnter:()=>i&&gsap.to(gsap.utils.toArray('.protocol-card')[i-1],{scale:.9,filter:'blur(20px)',opacity:.5,duration:.45}),onLeaveBack:()=>i&&gsap.to(gsap.utils.toArray('.protocol-card')[i-1],{scale:1,filter:'blur(0px)',opacity:1,duration:.45})})})});return()=>ctx.revert()},[]);return <><Navbar/><Hero/><Features/><Manifesto/><Protocol/><Membership/></>}
